modid = "ioticblocks"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    "{$_fabric.src}/main/resources",
    { path="{$_fabric.src}/generated/resources", required=false },
    "{$_forge.src}/main/resources",
    { path="{$_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_ioticblocks/_export/generated"

[template]
icon = "{$_common.src}/main/resources/assets/ioticblocks/icon.png"
include = [
    "ioticblocks",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "IoticBlocks"
author = "object-Object"
show_landing_text = false

[template.args.navbar]
center = [
    { text="API Docs", href.variable="ioticblocks_api_docs_url" },
    { text="GitHub", href.variable="source_url" },
]

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='(?P<is_per_world>make|makePerWorld)\("(?P<name>[^"]+)",\s*HexDir\.(?P<startdir>\w+),\s*"(?P<signature>[qweasd]+)"' }
_per_world_value = "makePerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.kotlin}/registry/IoticBlocksActions.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../common/src"
java = "{src}/main/java/gay/object/ioticblocks"
kotlin = "{src}/main/kotlin/gay/object/ioticblocks"

[_fabric]
src = "../fabric/src"
java = "{src}/main/java/gay/object/ioticblocks/fabric"
kotlin = "{src}/main/kotlin/gay/object/ioticblocks/fabric"

[_forge]
src = "../forge/src"
java = "{src}/main/java/gay/object/ioticblocks/forge"
kotlin = "{src}/main/kotlin/gay/object/ioticblocks/forge"
