name: Build the web book

on:
  push:
    branches: "*"
  workflow_dispatch:

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  MAIN_BRANCHES: '["main"]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      is-main-branch: |-
        ${{
          github.event_name != 'pull_request'
          && contains(fromJson(env.MAIN_BRANCHES), env.BRANCH_NAME)
        }}
    steps:
      - name: Print message so the workflow isn't invalid
        run: 'echo "Hello World!"'

  build-docs:
    needs: setup
    uses: hexdoc-dev/actions/.github/workflows/hexdoc.yml@v1
    permissions:
      contents: write
      pages: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python-version: 3.11
      deploy-pages: ${{ needs.setup.outputs.is-main-branch == 'true' }}
      release: false
