name: Build the web book

on:
  push:
    branches: "*"
  workflow_dispatch:

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  MAIN_BRANCHES: '["main"]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      is-main-branch: |-
        ${{
          github.event_name != 'pull_request'
          && contains(fromJson(env.MAIN_BRANCHES), env.BRANCH_NAME)
        }}
    steps:
      - name: Print message so the workflow isn't invalid
        run: 'echo "Hello World!"'

  build-hexdoc:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read
    outputs:
      pages-url: ${{ steps.build.outputs.pages-url }}
    steps:
      - uses: actions/checkout@v4

      - uses: hexdoc-dev/actions/setup@v1
        with:
          python-version: 3.11

      - id: build
        uses: hexdoc-dev/actions/build@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release: false
  
  build-dokka:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4

      - name: Run Dokka
        run: ./gradlew :dokkaGenerate
      
      - name: Upload Dokka artifact
        uses: actions/upload-artifact@v4
        with:
          name: dokka-pages
          path: build/dokka/html
  
  deploy-pages:
    needs:
      - setup
      - build-hexdoc
      - build-dokka
    if: needs.setup.outputs.is-main-branch == 'true'
    runs-on: ubuntu-latest
    concurrency:
      group: hexdoc-deploy-pages
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: hexdoc-dev/actions/setup@v1
        with:
          python-version: 3.11
        
      - name: Merge new hexdoc build into existing book
        uses: hexdoc-dev/actions/merge@v1
        with:
          release: false
          site-url: ${{ needs.build-hexdoc.outputs.pages-url }}
      
      - name: Remove old Dokka site
        run: rm -rf _site/dst/docs/api

      - name: Download Dokka artifact
        uses: actions/download-artifact@v4
        with:
          name: dokka-pages
          path: _site/dst/docs/api
      
      - name: Deploy to Pages
        uses: hexdoc-dev/actions/deploy-pages@v1
        with:
          merge: false
          release: false
