name: Build pull request

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3

      - name: Build mod
        run: ./gradlew build

      # literally no idea why the mkdir is needed, but the workflow fails without it :/
      - name: Check if datagen needs to be run
        timeout-minutes: 3
        run: |
          mkdir -p /home/runner/.gradle/caches/fabric-loom/assets
          ./gradlew runAllDatagen
          git add --intent-to-add .
          git diff --name-only --exit-code -- ":!:*/src/generated/resources/.cache/*"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: build/jenkinsArtifacts/
          if-no-files-found: error

  build-docs:
    uses: hexdoc-dev/actions/.github/workflows/hexdoc.yml@v1
    permissions:
      contents: read
      pages: read
    secrets:
      GH_TOKEN: ''
    with:
      python-version: 3.11
      deploy-pages: false
      release: false
